[33mWARNING: Non existent mount point (file) in container: '/var/singularity/mnt/final/usr/bin/nvidia-debugdump'
[0m[33mWARNING: Non existent mount point (file) in container: '/var/singularity/mnt/final/usr/bin/nvidia-persistenced'
[0m[33mWARNING: Non existent mount point (file) in container: '/var/singularity/mnt/final/usr/bin/nvidia-cuda-mps-control'
[0m[33mWARNING: Non existent mount point (file) in container: '/var/singularity/mnt/final/usr/bin/nvidia-cuda-mps-server'
[0m/home/ucapnje
/home/ucapnje/share/DeepMass/run_scripts
loading mask 

(256, 256)
Loading input data
847.1739716529846
Loading clean data
1416.7838475704193
Using TensorFlow backend.
Traceback (most recent call last):
  File "test_wiener_prototype.py", line 56, in <module>
    print('Test loss weighted = ' + str(mf.mean_square_error(test_array_clean.flatten(), test_array_noisy.flatten(), weights=1.0/np.var(test_array_clean.flatten()))))
  File "../deepmass/map_functions.py", line 287, in mean_square_error
    return np.average((y_pred.flatten() - y_true.flatten())**2., weights=weights)
  File "/anaconda/envs/tensorflow/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1142, in average
    "Axis must be specified when shapes of a and weights "
TypeError: Axis must be specified when shapes of a and weights differ.
